# Generated by Django 6.0 on 2025-12-30 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_attendancesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('service', 'Church Service'), ('bible_study', 'Bible Study'), ('prayer', 'Prayer Meeting'), ('youth', 'Youth Meeting'), ('outreach', 'Outreach'), ('social', 'Social Event'), ('training', 'Training'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_all_day', models.BooleanField(default=False)),
                ('venue', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('online_link', models.URLField(blank=True)),
                ('expected_participants', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('send_reminder', models.BooleanField(default=True)),
                ('reminder_days', models.IntegerField(default=1)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('documents', models.FileField(blank=True, null=True, upload_to='event_docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('attended', 'Attended'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('number_of_guests', models.IntegerField(default=0)),
                ('special_requirements', models.TextField(blank=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('check_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to='members.member')),
            ],
            options={
                'unique_together': {('event', 'member')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(related_name='events', through='events.EventRegistration', to='members.member'),
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='events.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'unique_together': {('event', 'member')},
            },
        ),
    ]
