# Generated by Django 6.0 on 2025-12-30 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_attendancesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('donor_name', models.CharField(blank=True, max_length=200)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('donor_phone', models.CharField(blank=True, max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donation_type', models.CharField(choices=[('tithe', 'Tithe'), ('offering', 'Offering'), ('seed', 'Seed/Sowing'), ('building', 'Building Fund'), ('missions', 'Missions'), ('benevolence', 'Benevolence'), ('other', 'Other')], max_length=50)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('check', 'Check'), ('online', 'Online Payment')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('donation_date', models.DateField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='members.member')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-donation_date', '-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donation_type', models.CharField(choices=[('tithe', 'Tithe'), ('offering', 'Offering'), ('seed', 'Seed/Sowing'), ('building', 'Building Fund'), ('missions', 'Missions'), ('benevolence', 'Benevolence'), ('other', 'Other')], max_length=50)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('check', 'Check'), ('online', 'Online Payment')], max_length=50)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_payment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_donations', to='members.member')),
            ],
            options={
                'ordering': ['member', '-next_payment_date'],
            },
        ),
    ]
