# Generated by Django 5.2.9 on 2025-12-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook/Hotmail'), ('yahoo', 'Yahoo'), ('sendgrid', 'SendGrid'), ('custom', 'Custom SMTP')], default='gmail', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=200)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.EmailField(blank=True, max_length=254)),
                ('smtp_password', models.CharField(blank=True, max_length=100)),
                ('from_email', models.EmailField(default='noreply@yourchurch.com', max_length=254)),
                ('from_name', models.CharField(default='Youth Church', max_length=100)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('test_email', models.EmailField(blank=True, help_text='Email to send test messages to', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Configuration',
                'verbose_name_plural': 'Email Configuration',
            },
        ),
        migrations.CreateModel(
            name='SMSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('twilio', 'Twilio'), ('africastalking', "Africa's Talking"), ('termii', 'Termii'), ('hubtel', 'Hubtel'), ('manual', 'Manual/Manual')], default='manual', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('twilio_account_sid', models.CharField(blank=True, max_length=100)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=100)),
                ('twilio_phone_number', models.CharField(blank=True, max_length=20)),
                ('africastalking_username', models.CharField(blank=True, max_length=100)),
                ('africastalking_api_key', models.CharField(blank=True, max_length=100)),
                ('africastalking_sender_id', models.CharField(blank=True, max_length=20)),
                ('default_sender_name', models.CharField(default='Church', max_length=50)),
                ('cost_per_sms', models.DecimalField(decimal_places=2, default=0.05, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Configuration',
                'verbose_name_plural': 'SMS Configuration',
            },
        ),
    ]
