# Generated by Django 5.2.9 on 2026-02-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_emailconfiguration_smsconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsconfiguration',
            name='arkesel_api_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='smsconfiguration',
            name='arkesel_sender_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='smsconfiguration',
            name='provider',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('africastalking', "Africa's Talking"), ('arkesel', 'Arkesel'), ('termii', 'Termii'), ('hubtel', 'Hubtel'), ('manual', 'Manual/Manual')], default='manual', max_length=50),
        ),
    ]
