# Generated by Django 5.2.9 on 2026-02-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_smsconfiguration_arkesel_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsconfiguration',
            name='africastalking_api_url',
            field=models.URLField(blank=True, default='https://api.africastalking.com/version1', help_text="Africa's Talking API base URL", max_length=500),
        ),
        migrations.AddField(
            model_name='smsconfiguration',
            name='arkesel_api_url',
            field=models.URLField(blank=True, default='https://sms.arkesel.com/sms/api', help_text='Arkesel API endpoint (v1: sms/api, v2: api/v2/sms/send)', max_length=500),
        ),
        migrations.AddField(
            model_name='smsconfiguration',
            name='twilio_api_url',
            field=models.URLField(blank=True, default='https://api.twilio.com/2010-04-01/Accounts', help_text='Twilio API base URL', max_length=500),
        ),
    ]
