# Generated by Django 6.0.1 on 2026-05-04 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_message_deleted_at_message_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name for reference', max_length=100)),
                ('template_type', models.CharField(choices=[('broadcast', 'Broadcast Template'), ('group', 'Group Message Template'), ('individual', 'Individual Message Template'), ('sms', 'SMS Template'), ('email', 'Email Template')], default='broadcast', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Subject line (for email templates)', max_length=200)),
                ('content', models.TextField(help_text='Template content. Use {name}, {member_name}, {date} for placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, help_text='e.g., Event, Reminder, Announcement', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Notes about when to use this template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'ordering': ['template_type', 'category', 'name'],
            },
        ),
    ]
