# Generated by Django 6.0.1 on 2026-05-10 00:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_create_default_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='allow_member_replies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='messageresponse',
            name='respondent_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
