"""
Django settings for church_youth_system project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

"""
Django settings for church_youth_system project.
"""

import os
import importlib.util
from pathlib import Path
from decouple import config


def _module_available(module_name):
    return importlib.util.find_spec(module_name) is not None


HAS_DJANGO_REDIS = _module_available('django_redis')
HAS_CACHALOT = _module_available('cachalot')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
IS_VERCEL = bool(os.environ.get('VERCEL')) or bool(os.environ.get('VERCEL_ENV'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-fallback-change-in-vercel-env')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'yourdomain.com',
    '.vercel.app',
]

extra_allowed_hosts = config('ALLOWED_HOSTS', default='')
if extra_allowed_hosts:
    ALLOWED_HOSTS.extend(
        host.strip() for host in extra_allowed_hosts.split(',') if host.strip()
    )

vercel_url = config('VERCEL_URL', default='').strip()
if vercel_url:
    ALLOWED_HOSTS.append(vercel_url)

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'import_export',
    'phonenumber_field',
    'simple_history',

    # Local apps
    'members.apps.MembersConfig',
    'messaging.apps.MessagingConfig',
    'portal.apps.PortalConfig',

    'accounts',
    'events',
    'prayer',
    'giving',
    'notifications',
]

if HAS_CACHALOT:
    INSTALLED_APPS.append('cachalot')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

ROOT_URLCONF = 'church_youth_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'church_youth_system.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASES['sqlite'] = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'db.sqlite3',
}

# Support for DATABASE_URL (Neon / Vercel Postgres / other providers)
try:
    import dj_database_url
except Exception:
    dj_database_url = None

DATABASE_URL = config('DATABASE_URL', default=None)
if DATABASE_URL and dj_database_url:
    DATABASES['default'] = dj_database_url.parse(
        DATABASE_URL, conn_max_age=600, ssl_require=True)
elif config('PGDATABASE', default=''):
    # Fallback to individual PG* env vars when provided
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('PGDATABASE', default=config('POSTGRES_DATABASE', default='church_youth_db')),
        'USER': config('PGUSER', default=config('POSTGRES_USER', default='youth_admin')),
        'PASSWORD': config('PGPASSWORD', default=config('POSTGRES_PASSWORD', default='')),
        'HOST': config('PGHOST', default=config('POSTGRES_HOST', default='')),
        'PORT': config('PGPORT', default='5432'),
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Caching Configuration
REDIS_URL = config('REDIS_URL', default='redis://localhost:6379/1')
CACHES = (
    {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
                'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                'IGNORE_EXCEPTIONS': True,  # Fail gracefully if Redis is down
            }
        }
    }
    if HAS_DJANGO_REDIS else
    {
        # Safe fallback so local/dev environments still boot without django-redis.
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'church-youth-local-cache',
            'TIMEOUT': 60 * 5,
        }
    }
)

# Cachalot Configuration (ORM Query Caching)
CACHALOT_ENABLE = (not DEBUG) and HAS_CACHALOT
CACHALOT_TIMEOUT = 60 * 5  # 5 minutes

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

if IS_VERCEL:
    # Vercel build output may not contain a populated STATIC_ROOT directory.
    # Use finder-based serving to keep Django admin/static assets available.
    WHITENOISE_USE_FINDERS = True
    WHITENOISE_AUTOREFRESH = True

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

if IS_VERCEL:
    # Vercel filesystem is read-only except /tmp.
    MEDIA_ROOT = Path('/tmp/media')

# Vercel / production static & media settings
# Use Whitenoise for static files in production
if not DEBUG:
    # Vercel deployments in this project do not run collectstatic in a persistent artifact.
    # Use non-manifest storage in hosted runtime to avoid startup/runtime 500 errors.
    if IS_VERCEL:
        STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
    else:
        STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    WHITENOISE_MANIFEST_STRICT = False

# Blob / object storage tokens (Vercel Blob or similar)
# Set these in Vercel dashboard when using Vercel Blob or other provider
VERCEL_BLOB_TOKEN = config('VERCEL_BLOB_TOKEN', default='')
BLOB_READ_WRITE_TOKEN = config('BLOB_READ_WRITE_TOKEN', default='')
VERCEL_BLOB_BASE_URL = config('VERCEL_BLOB_BASE_URL', default='')
USE_VERCEL_BLOB_STORAGE = config(
    'USE_VERCEL_BLOB_STORAGE', default=False, cast=bool)

blob_token = BLOB_READ_WRITE_TOKEN or VERCEL_BLOB_TOKEN

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if (not DEBUG and IS_VERCEL) else
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
            if not DEBUG else
            'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
    },
}

if (USE_VERCEL_BLOB_STORAGE or IS_VERCEL) and blob_token:
    STORAGES['default'] = {
        'BACKEND': 'church_youth_system.storage_backends.VercelBlobStorage',
    }

# If you plan to use S3-compatible storage (django-storages + boto3),
# add `DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'`
# and set the relevant AWS_* or S3_ENDPOINT variables in Vercel.

# File upload permissions
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Login settings
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
LOGIN_URL = '/accounts/login/'

# Phone number field
PHONENUMBER_DB_FORMAT = 'INTERNATIONAL'
PHONENUMBER_DEFAULT_REGION = 'GH'  # Change to your country code


# Email settings (for password reset)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_PHONE_NUMBER = config('TWILIO_PHONE_NUMBER', default='')

AFRICASTALKING_USERNAME = config('AFRICASTALKING_USERNAME', default='')
AFRICASTALKING_API_KEY = config('AFRICASTALKING_API_KEY', default='')

# Email settings for production
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL', default='noreply@yourchurch.com')


if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
