from django.urls import path
from . import views

urlpatterns = [
    path('', views.admin_portal, name='admin_portal'),
    path('search/', views.member_search, name='member_search'),
    path('member/add/', views.add_member, name='add_member'),
    path('member/<int:pk>/', views.member_detail, name='member_detail'),
    path('member/<int:pk>/edit/', views.edit_member, name='edit_member'),
    path('messaging/', views.messaging_dashboard, name='messaging_dashboard'),
    path('messaging/compose/', views.compose_message, name='compose_message'),
    path('messaging/<uuid:message_id>/reply/<int:member_id>/<uuid:token>/', views.member_message_reply, name='member_message_reply'),
    path('messaging/status/', views.messaging_status, name='messaging_status'),
    path('quick-announcement/', views.quick_announcement,
         name='quick_announcement'),
    path('messaging/<uuid:message_id>/delete/',
         views.delete_message, name='delete_message'),
    path('messaging/<uuid:message_id>/restore/',
         views.restore_message, name='restore_message'),
    path('messaging/<uuid:message_id>/permanently-delete/',
         views.permanently_delete_message, name='permanently_delete_message'),
    path('messaging/<uuid:message_id>/responses/',
         views.message_responses, name='message_responses'),
    path('messaging/responses/<int:response_id>/delete/',
         views.delete_message_response, name='delete_message_response'),
    path('messaging/responses/<int:response_id>/restore/',
         views.restore_message_response, name='restore_message_response'),
    path('messaging/responses/<int:response_id>/permanently-delete/',
         views.permanently_delete_message_response, name='permanently_delete_message_response'),
    path('messaging/bulk-delete/', views.bulk_delete_messages,
         name='bulk_delete_messages'),
    path('messaging/bulk-delete-responses/',
         views.bulk_delete_responses, name='bulk_delete_responses'),
    path('messaging/trash/', views.trash_view, name='trash_view'),
    path('member/<int:member_id>/messages/',
         views.member_messages, name='member_messages'),
    path('analytics/', views.analytics_dashboard, name='analytics_dashboard'),
    path('ajax/search-members/', views.ajax_search_members,
         name='ajax_search_members'),
    path('export-members-csv/', views.export_members_csv,
         name='export_members_csv'),
    path('quick-attendance/', views.quick_attendance, name='quick_attendance'),
    path('ajax/check-attendance/', views.check_attendance, name='check_attendance'),
    path('attendance/history/', views.attendance_history,
         name='attendance_history'),
    path('attendance/<int:attendance_id>/delete/',
         views.delete_attendance, name='delete_attendance'),
    path('attendance/<int:attendance_id>/restore/',
         views.restore_attendance, name='restore_attendance'),
    path('attendance/<int:attendance_id>/permanently-delete/',
         views.permanently_delete_attendance, name='permanently_delete_attendance'),
    path('attendance/<int:attendance_id>/edit/',
         views.edit_attendance, name='edit_attendance'),
    path('attendance/report/', views.attendance_report, name='attendance_report'),
    path('setup-sms-email/', views.setup_sms_email, name='setup_sms_email'),
    path('send-test-message/', views.send_test_message, name='send_test_message'),

    path('birthday-tracker/', views.birthday_tracker, name='birthday_tracker'),
]
