# Generated by Django 6.0 on 2025-12-30 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=200)),
                ('session_type', models.CharField(choices=[('sunday_service', 'Sunday Service'), ('wednesday_service', 'Wednesday Service'), ('friday_service', 'Friday Service'), ('bible_study', 'Bible Study'), ('youth_meeting', 'Youth Meeting'), ('special_event', 'Special Event')], max_length=50)),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('total_present', models.IntegerField(default=0)),
                ('total_absent', models.IntegerField(default=0)),
                ('total_visitors', models.IntegerField(default=0)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_code_data', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_date', '-start_time'],
            },
        ),
    ]
